import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { CAPABILITIES, PlatformError } from '../src/shared/protocol.js';
import { PluginManager } from './plugin-manager.js';
import { GenerationTaskQueue } from './generation-queue.js';

const json = async (file) => JSON.parse(await fs.readFile(file, 'utf8'));
const now = () => new Date().toISOString();
const id = (prefix) => `${prefix}_${crypto.randomUUID()}`;

export class WorkbenchRuntime {
  constructor(root, options = {}) { this.root = root; this.dataDir = path.join(root, 'data'); this.tasks = new Map(); this.modules = []; this.quarantine = []; this.templates = []; this.pluginManager = new PluginManager(root, options.pluginRoot); this.generationQueue = null; this.debugLogPath = path.join(this.dataDir, 'logs', 'image2-trace.ndjson'); }
  async initialize() { await this.loadServerEnv(); this.generationQueue = new GenerationTaskQueue({ concurrency: Number(process.env.GENERATION_CONCURRENCY || process.env.MAX_CONCURRENCY || 2) }); for (const dir of ['assets', 'history', 'logs', 'registry', 'uploads', 'results']) await fs.mkdir(path.join(this.dataDir, dir), { recursive: true }); await this.discoverModules(); await this.pluginManager.initialize(); await this.loadHistory(); await this.loadTemplates(); }
  async debugLog(event) { try { await fs.appendFile(this.debugLogPath, `${JSON.stringify({ at: now(), ...event })}\n`, 'utf8'); } catch {} }
  async loadServerEnv() { try { const text = await fs.readFile(path.join(this.root, '.env'), 'utf8'); for (const line of text.split(/\r?\n/)) { const match = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/); if (match && !process.env[match[1]]) process.env[match[1]] = match[2].replace(/^['"]|['"]$/g, ''); } } catch {} }
  config() { return { providers: { image2: Boolean(process.env.OPENAI_API_KEY), nanoBanana: Boolean(process.env.OPENLUX_API_KEY || process.env.GOOGLE_API_KEY) }, defaultProvider: process.env.DEFAULT_IMAGE_PROVIDER || 'image2', outputDir: this.dataDir, maxConcurrency: this.generationQueue?.concurrency || Number(process.env.MAX_CONCURRENCY || 2), imageSizes: this.imageSizeOptions() }; }
  async loadTemplates() { try { this.templates = JSON.parse(await fs.readFile(path.join(this.dataDir, 'templates.json'), 'utf8')); } catch { this.templates = [{ id: 'tpl_standing', category: '站姿', name: '自然站立', prompt: '自然站立，身体舒展，正面全身构图', negativePrompt: '畸形手指，额外肢体，扭曲身体', providers: ['image2', 'nano_banana'], favorite: true }]; await this.persistTemplates(); } }
  async persistTemplates() { await fs.writeFile(path.join(this.dataDir, 'templates.json'), JSON.stringify(this.templates, null, 2)); }
  async createTemplate(input) { const template = { id: id('tpl'), category: input.category || '未分类', name: input.name || '未命名动作', prompt: input.prompt || '', negativePrompt: input.negativePrompt || '', providers: input.providers || ['image2', 'nano_banana'], favorite: Boolean(input.favorite), createdAt: now(), updatedAt: now() }; this.templates.unshift(template); await this.persistTemplates(); return template; }
  async updateTemplate(templateId, input) { const template = this.templates.find((item) => item.id === templateId); if (!template) throw new PlatformError('TEMPLATE_NOT_FOUND', '动作模板不存在。'); Object.assign(template, input, { updatedAt: now() }); await this.persistTemplates(); return template; }
  async createUpload(input) { if (!input.data || !String(input.data).includes(',')) throw new PlatformError('UPLOAD_INVALID', '图片数据无效。'); const assetId = id('asset'); const mimeType = input.mimeType || 'image/png'; const ext = mimeType.split('/')[1]?.replace('jpeg', 'jpg') || 'png'; const localPath = path.join(this.dataDir, 'uploads', `${assetId}.${ext}`); await fs.writeFile(localPath, Buffer.from(String(input.data).split(',').pop(), 'base64')); const asset = { assetId, name: input.name || `${assetId}.${ext}`, localPath, mimeType, url: `/api/assets/${assetId}`, createdAt: now() }; await fs.writeFile(path.join(this.dataDir, 'registry', `${assetId}.json`), JSON.stringify(asset, null, 2)); return asset; }
  async createGeneration(input) { const count = [1, 2, 4, 10].includes(Number(input.outputCount)) ? Number(input.outputCount) : 1; const images = Array.from({ length: count }, (_, index) => ({ id: id('result'), index, status: 'waiting' })); const provider = input.provider || 'image2'; const requestedResolution = input.settings?.resolution || 'auto'; const autoResolution = provider === 'image2' && requestedResolution === 'auto' && input.referenceAssetIds?.length ? await this.referenceResolutionFor(input.referenceAssetIds[0]) : 'auto'; const resolutionTier = ['1K', '2K', '4K'].includes(input.settings?.resolutionTier) ? input.settings.resolutionTier : null; const settings = { mode: input.settings?.mode || input.mode || 'image_to_image', aspectRatio: input.settings?.aspectRatio || input.ratio || 'auto', resolutionTier, resolution: autoResolution === 'auto' ? requestedResolution : autoResolution, quality: input.settings?.quality || 'auto', background: input.settings?.background || 'auto' }; const resolution = provider === 'nano_banana' ? (settings.resolutionTier || '1K') : this.gptSizeFor(settings); const task = { taskId: id('task'), requestId: id('req'), type: settings.mode, provider, model: this.modelFor(provider), resolution, imageRatio: provider === 'nano_banana' ? settings.aspectRatio : this.ratioForSize(resolution), prompt: input.prompt || '', negativePrompt: input.negativePrompt || '', referenceAssetIds: input.referenceAssetIds || [], actionTemplateId: input.actionTemplateId || null, settings, requestedImageCount: count, outputCount: count, status: 'queued', progress: 0, results: images, images, createdAt: now(), updatedAt: now() }; await this.debugLog({ phase: 'task.created', requestId: task.requestId, taskId: task.taskId, provider: task.provider, outputCount: count, prompt: task.prompt, settings, referenceCount: task.referenceAssetIds.length }); this.tasks.set(task.taskId, task); await this.persistTask(task); queueMicrotask(() => this.runGeneration(task)); return task; }
  async runGeneration(task) { task.status = 'processing'; task.updatedAt = now(); await this.persistTask(task); const jobs = Array.from({ length: task.requestedImageCount }, (_, index) => this.generationQueue.add(async () => { const result = task.images[index]; result.status = 'running'; result.startedAt = now(); task.updatedAt = now(); await this.persistTask(task); try { const asset = await this.generateImage(task, index); Object.assign(result, asset, { status: 'success', completedAt: now() }); } catch (error) { Object.assign(result, { status: 'failed', error: error.message, completedAt: now() }); } task.progress = Math.round((task.images.filter((item) => ['success', 'failed'].includes(item.status)).length / task.requestedImageCount) * 100); task.updatedAt = now(); await this.persistTask(task); return result; })); await Promise.allSettled(jobs); task.status = task.images.every((item) => item.status === 'success') ? 'completed' : task.images.some((item) => item.status === 'success') ? 'partial' : 'failed'; task.completedAt = now(); task.durationMs = Date.parse(task.completedAt) - Date.parse(task.createdAt); task.updatedAt = task.completedAt; await this.persistTask(task); }
  async generateImage(task, index) {
    const outputId = id('result'); const outputPath = path.join(this.dataDir, 'results', `${outputId}.png`);
    if (task.provider === 'image2' && process.env.OPENAI_API_KEY) return this.generateWithImage2(task, outputId, outputPath);
    if (task.provider === 'nano_banana' && (process.env.OPENLUX_API_KEY || process.env.GOOGLE_API_KEY)) return this.generateWithNanoBanana(task, outputId, outputPath);
    return this.createDemoAsset({ ...task, input: { prompt: task.prompt }, taskId: `${task.taskId}_${index}` }, { manifest: { name: task.type } });
  }
  async generateWithImage2(task, outputId, outputPath) {
    const configuredBase = (process.env.LLM_BASE_URL || 'https://api.openai.com/v1').replace(/\/$/, ''); const base = configuredBase.replace(/\/images\/(?:edits|generations)$/i, ''); const refs = await Promise.all((task.referenceAssetIds || []).map((assetId) => this.asset(assetId))); const mode = refs.length ? 'image-to-image' : 'text-to-image'; const endpoint = process.env.OPENAI_IMAGE_GENERATION_URL || (refs.length ? process.env.OPENAI_IMAGE_EDIT_URL : null) || `${base}/images/${refs.length ? 'edits' : 'generations'}`; const settings = task.settings || {}; const requestMeta = { phase: 'provider.request', requestId: task.requestId, taskId: task.taskId, provider: 'image2', mode, method: 'POST', url: endpoint, model: process.env.OPENAI_IMAGE_MODEL || 'gpt-image-2', headers: { authorizationPresent: Boolean(process.env.OPENAI_API_KEY), contentType: refs.length ? 'multipart/form-data' : 'application/json' }, body: { prompt: task.prompt, size: this.gptSizeFor(settings), quality: settings.quality || 'auto', background: settings.background || 'auto', moderation: 'low', referenceCount: refs.length } }; await this.debugLog(requestMeta);
    try { let response; const timeout = AbortSignal.timeout(Number(process.env.PROVIDER_TIMEOUT_MS || 180000)); const settings = task.settings || {}; const size = this.gptSizeFor(settings); if (refs.length) { const form = new FormData(); form.set('model', requestMeta.model); form.set('prompt', task.prompt); form.set('size', size); form.set('quality', settings.quality || 'auto'); form.set('background', settings.background || 'auto'); form.set('moderation', 'low'); for (const ref of refs) form.append('image[]', new Blob([await fs.readFile(ref.localPath)], { type: ref.mimeType || 'image/png' }), path.basename(ref.localPath)); response = await fetch(endpoint, { method: 'POST', headers: { Authorization: `Bearer ${process.env.OPENAI_API_KEY}` }, body: form, signal: timeout }); } else response = await fetch(endpoint, { method: 'POST', headers: { Authorization: `Bearer ${process.env.OPENAI_API_KEY}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ model: requestMeta.model, prompt: task.prompt, size, quality: settings.quality || 'auto', background: settings.background || 'auto', moderation: 'low' }), signal: timeout }); const raw = await response.text(); let data; try { data = raw ? JSON.parse(raw) : {}; } catch { data = { raw }; } await this.debugLog({ phase: 'provider.response', requestId: task.requestId, taskId: task.taskId, provider: 'image2', status: response.status, ok: response.ok, body: typeof raw === 'string' ? raw.slice(0, 4000) : raw }); if (!response.ok) throw new Error(data?.error?.message || `image2 API ${response.status}`); await this.writeProviderImage(data, outputPath); return { assetId: outputId, url: `/api/assets/${outputId}`, localPath: outputPath, mimeType: 'image/png', providerDetails: { mode, endpoint } }; } catch (error) { await this.debugLog({ phase: 'provider.error', requestId: task.requestId, taskId: task.taskId, provider: 'image2', error: { name: error.name, message: error.message, cause: error.cause ? { name: error.cause.name, message: error.cause.message, code: error.cause.code, errno: error.cause.errno, syscall: error.cause.syscall } : null, stack: error.stack } }); throw error; }
  }
  async generateWithNanoBanana(task, outputId, outputPath) {
    const configuredBase = (process.env.OPENLUX_BASE_URL || 'https://api.openlux.ai/v1').replace(/\/$/, ''); const base = configuredBase.replace(/\/v1$/, ''); const model = process.env.OPENLUX_IMAGE_MODEL || process.env.GOOGLE_IMAGE_MODEL || 'gemini-2.5-flash-image'; const settings = task.settings || {}; const imageConfig = { imageSize: settings.resolutionTier || '1K' }; if ((settings.aspectRatio || task.ratio || 'auto') !== 'auto') imageConfig.aspectRatio = settings.aspectRatio || task.ratio; const endpoint = `${base}/v1beta/models/${encodeURIComponent(model)}:generateContent`; const body = { contents: [{ role: 'user', parts: [{ text: task.prompt }] }], generationConfig: { responseModalities: ['IMAGE'], imageConfig } }; await this.debugLog({ phase: 'provider.request', requestId: task.requestId, taskId: task.taskId, provider: 'nano_banana', method: 'POST', url: endpoint, model, body: { imageConfig } }); let response; let data; for (let attempt = 0; attempt < 3; attempt += 1) { response = await fetch(endpoint, { method: 'POST', headers: { Authorization: `Bearer ${process.env.OPENLUX_API_KEY || process.env.GOOGLE_API_KEY}`, 'Content-Type': 'application/json' }, body: JSON.stringify(body), signal: AbortSignal.timeout(Number(process.env.PROVIDER_TIMEOUT_MS || 180000)) }); data = await response.json(); const message = data?.error?.message || ''; if (response.ok || !/saturat|overload|temporar|rate limit/i.test(message)) break; await new Promise((resolve) => setTimeout(resolve, 1500 * (attempt + 1))); } await this.debugLog({ phase: 'provider.response', requestId: task.requestId, taskId: task.taskId, provider: 'nano_banana', status: response.status, ok: response.ok, body: { hasImage: Boolean(data?.candidates?.[0]?.content?.parts?.some((part) => part.inlineData?.data)) } }); if (!response.ok) throw new Error(data?.error?.message || `Nano Banana API ${response.status}`); await this.writeNanoBananaImage(data, outputPath); return { assetId: outputId, url: `/api/assets/${outputId}`, localPath: outputPath, mimeType: 'image/png', providerDetails: { mode: task.type, endpoint, imageConfig, attempts: 1 } };
  }
  async writeNanoBananaImage(data, outputPath) { const inlineData = data?.candidates?.[0]?.content?.parts?.find((part) => typeof part?.inlineData?.data === 'string')?.inlineData?.data; const content = data?.choices?.[0]?.message?.content; const match = typeof content === 'string' ? content.match(/data:image\/[^;]+;base64,([A-Za-z0-9+/=]+)/) : null; const source = inlineData || match?.[1]; if (!source) throw new Error('Google provider response did not contain an image.'); await fs.writeFile(outputPath, Buffer.from(source, 'base64')); }
  async writeProviderImage(data, outputPath) { const find = (value) => { if (!value) return null; if (typeof value === 'string' && value.startsWith('data:image/')) return value; if (typeof value === 'string' && /^https?:\/\//.test(value)) return value; if (typeof value === 'object') { if (value.b64_json) return `data:image/png;base64,${value.b64_json}`; for (const item of Object.values(value)) { const found = find(item); if (found) return found; } } return null; }; const source = find(data); if (!source) throw new Error('Provider response did not contain an image.'); const buffer = source.startsWith('data:') ? Buffer.from(source.split(',')[1], 'base64') : Buffer.from(await (await fetch(source)).arrayBuffer()); await fs.writeFile(outputPath, buffer); }
  imageSizeOptions() { const prefix = 'OPENAI_IMAGE_SIZE_'; return Object.entries(process.env).filter(([key]) => key.startsWith(prefix)).map(([key, size]) => ({ id: key.slice(prefix.length).toLowerCase(), label: key.slice(prefix.length).replaceAll('_', ' '), size })).filter(({ size }) => this.isValidImageSize(size)).sort((left, right) => (left.id === 'auto' ? -1 : right.id === 'auto' ? 1 : left.id.localeCompare(right.id))); }
  isValidImageSize(size) { if (size === 'auto') return true; const match = String(size).match(/^(\d+)x(\d+)$/); if (!match) return false; const [width, height] = match.slice(1).map(Number); const multiple = Number(process.env.IMAGE_SIZE_MULTIPLE_PX || 16); const maxEdge = Number(process.env.IMAGE_MAX_EDGE_PX || 3840); const maxRatio = Number(process.env.IMAGE_MAX_ASPECT_RATIO || 3); return width > 0 && height > 0 && width <= maxEdge && height <= maxEdge && width % multiple === 0 && height % multiple === 0 && Math.max(width, height) / Math.min(width, height) <= maxRatio; }
  async referenceResolutionFor(assetId) { try { const asset = await this.asset(assetId); const dimensions = this.imageDimensions(await fs.readFile(asset.localPath)); if (!dimensions) return 'auto'; const candidates = this.imageSizeOptions().filter((option) => option.size !== 'auto').map((option) => ({ ...option, dimensions: option.size.split('x').map(Number) })); return candidates.reduce((best, option) => { const score = Math.abs(Math.log(option.dimensions[0] / dimensions.width)) + Math.abs(Math.log(option.dimensions[1] / dimensions.height)); return !best || score < best.score ? { id: option.id, score } : best; }, null)?.id || 'auto'; } catch { return 'auto'; } }
  imageDimensions(buffer) { if (buffer.length >= 24 && buffer.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]))) return { width: buffer.readUInt32BE(16), height: buffer.readUInt32BE(20) }; if (buffer.length >= 30 && buffer.subarray(0, 4).toString() === 'RIFF' && buffer.subarray(8, 12).toString() === 'WEBP') { const type = buffer.subarray(12, 16).toString(); if (type === 'VP8X') return { width: 1 + buffer.readUIntLE(24, 3), height: 1 + buffer.readUIntLE(27, 3) }; if (type === 'VP8 ' && buffer.subarray(23, 26).equals(Buffer.from([157, 1, 42]))) return { width: buffer.readUInt16LE(26) & 0x3fff, height: buffer.readUInt16LE(28) & 0x3fff }; if (type === 'VP8L' && buffer[20] === 47) return { width: 1 + buffer[21] + ((buffer[22] & 63) << 8), height: 1 + ((buffer[22] >> 6) | (buffer[23] << 2) | ((buffer[24] & 15) << 10)) }; } if (buffer.length >= 4 && buffer[0] === 255 && buffer[1] === 216) { for (let offset = 2; offset + 9 < buffer.length;) { if (buffer[offset] !== 255) { offset += 1; continue; } const marker = buffer[offset + 1]; const length = buffer.readUInt16BE(offset + 2); if ([192, 193, 194, 195, 197, 198, 199, 201, 202, 203].includes(marker)) return { width: buffer.readUInt16BE(offset + 7), height: buffer.readUInt16BE(offset + 5) }; offset += length + 2; } } return null; }
  sizeFor(ratio, resolution) { const configured = this.imageSizeOptions().find((option) => option.id === resolution); return configured?.size || ({ '1:1': '1024x1024', '3:4': '1024x1536', '4:3': '1536x1024', '16:9': '1536x1024', '9:16': '1024x1536' }[ratio] || '1024x1024'); }
  gptSizeFor(settings = {}) { const aspectRatio = settings.aspectRatio || settings.ratio || 'auto'; if (!settings.resolutionTier) return this.sizeFor(aspectRatio, settings.resolution || '1k'); if (aspectRatio === 'auto') return 'auto'; const tier = String(settings.resolutionTier).toLowerCase(); const target = aspectRatio.split(':').map(Number); const targetRatio = target.length === 2 && target.every(Number.isFinite) ? target[0] / target[1] : 1; const candidates = this.imageSizeOptions().filter((option) => option.id.startsWith(tier) && option.size !== 'auto'); if (!candidates.length) return this.sizeFor(aspectRatio, settings.resolution || '1k'); return candidates.reduce((best, option) => { const [width, height] = option.size.split('x').map(Number); const score = Math.abs(Math.log((width / height) / targetRatio)); return !best || score < best.score ? { size: option.size, score } : best; }, null).size; }
  modelFor(provider) { return provider === 'nano_banana' ? (process.env.OPENLUX_IMAGE_MODEL || process.env.GOOGLE_IMAGE_MODEL || 'gemini-2.5-flash-image') : (process.env.OPENAI_IMAGE_MODEL || 'gpt-image-2'); }
  ratioForSize(size) { const match = String(size).match(/^(\d+)x(\d+)$/); if (!match) return 'auto'; const [width, height] = match.slice(1).map(Number); const gcd = (left, right) => right ? gcd(right, left % right) : left; const divisor = gcd(width, height); return `${width / divisor}:${height / divisor}`; }
  async retryResult(resultId) { for (const task of this.tasks.values()) { const result = (task.images || task.results || []).find((item) => item.id === resultId); if (result) { result.status = 'waiting'; task.results = task.images = task.images || task.results; task.status = 'processing'; await this.persistTask(task); await this.generationQueue.add(async () => { result.status = 'running'; result.startedAt = now(); try { Object.assign(result, await this.generateImage(task, result.index), { status: 'success', completedAt: now() }); } catch (error) { Object.assign(result, { status: 'failed', error: error.message, completedAt: now() }); } }); task.status = task.images.every((item) => item.status === 'success') ? 'completed' : 'partial'; await this.persistTask(task); return task; } } throw new PlatformError('RESULT_NOT_FOUND', '结果不存在。'); }
  async discoverModules() {
    this.modules = []; this.quarantine = []; const base = path.join(this.root, 'modules'); let moduleDirs = [];
    try { moduleDirs = await fs.readdir(base, { withFileTypes: true }); } catch { return; }
    for (const moduleDir of moduleDirs.filter((entry) => entry.isDirectory())) {
      const versions = await fs.readdir(path.join(base, moduleDir.name), { withFileTypes: true });
      for (const version of versions.filter((entry) => entry.isDirectory())) { const dir = path.join(base, moduleDir.name, version.name); try { this.modules.push(await this.loadModule(dir)); } catch (error) { this.quarantine.push({ path: dir, error: error.message, code: error.code || 'MODULE_INVALID' }); } }
    }
    this.modules.sort((a, b) => a.manifest.name.localeCompare(b.manifest.name) || b.manifest.version.localeCompare(a.manifest.version));
  }
  async loadModule(dir) {
    const [manifest, ui, workflow, output] = await Promise.all(['manifest.json', 'ui.schema.json', 'workflow.json', 'output.schema.json'].map((name) => json(path.join(dir, name))));
    if (!manifest.moduleId || !manifest.name || !manifest.version) throw new PlatformError('MODULE_MANIFEST_INVALID', 'Manifest is missing required identity fields.');
    if (!Array.isArray(manifest.permissions) || manifest.permissions.some((permission) => !CAPABILITIES.has(permission))) throw new PlatformError('MODULE_PERMISSION_DENIED', 'Module requests a capability outside the platform whitelist.');
    if (!Array.isArray(ui.fields) || ui.fields.some((field) => !['image-upload', 'textarea', 'select', 'number', 'slider', 'switch'].includes(field.type))) throw new PlatformError('MODULE_UI_INVALID', 'UI schema contains an unsupported control.');
    if (!Array.isArray(workflow.steps) || workflow.steps.some((step) => !CAPABILITIES.has(step.action) || !manifest.permissions.includes(step.action))) throw new PlatformError('MODULE_WORKFLOW_INVALID', 'Workflow contains an undeclared or unsupported capability.');
    return { dir, key: `${manifest.moduleId}@${manifest.version}`, manifest, ui, workflow, output };
  }
  listModules() { return this.modules.map(({ key, manifest, ui }) => ({ key, manifest, ui })); }
  listPlugins() { return { plugins: this.pluginManager.list(), quarantine: this.pluginManager.quarantine }; }
  async refreshPlugins() { await this.pluginManager.discover(); return this.listPlugins(); }
  getModule(key) { const value = this.modules.find((module) => module.key === key); if (!value) throw new PlatformError('MODULE_NOT_FOUND', 'The requested module version is unavailable.'); return value; }
  async createTask({ moduleKey, input }) {
    const module = this.getModule(moduleKey);
    for (const field of module.ui.fields) { const value = input[field.id]; if (field.required && (value === undefined || value === null || value === '')) throw new PlatformError('INPUT_VALIDATION_FAILED', `${field.label} is required.`); }
    const provider = this.pluginManager.provider('image.generate');
    if (!provider) throw new PlatformError('PLUGIN_UNAVAILABLE', 'No healthy image.generate provider is enabled.', { retryable: true });
    const task = { taskId: id('task'), moduleId: module.manifest.moduleId, moduleVersion: module.manifest.version, moduleKey, pluginId: provider.manifest.pluginId, pluginVersion: provider.manifest.version, pluginKey: provider.key, status: 'queued', progress: 0, currentStep: null, input, outputs: [], apiCalls: 0, estimatedCost: module.manifest.resourceProfile?.estimatedCost || 0, createdAt: now(), updatedAt: now() };
    this.tasks.set(task.taskId, task); await this.persistTask(task); queueMicrotask(() => this.runTask(task, module)); return task;
  }
  async runTask(task, module) {
    task.status = 'running'; task.updatedAt = now(); await this.persistTask(task);
    try { for (const [index, step] of module.workflow.steps.entries()) { if (task.status === 'cancelled') return; task.currentStep = step.id; task.progress = Math.round((index / module.workflow.steps.length) * 100); await this.persistTask(task); if (step.action === 'image.generate') { await new Promise((resolve) => setTimeout(resolve, 650)); const asset = await this.createDemoAsset(task, module); task.outputs.push(asset); task.apiCalls += 1; } } task.status = 'completed'; task.progress = 100; task.updatedAt = now(); await this.persistTask(task); } catch (error) { task.status = 'failed'; task.error = this.errorFor(error, task); task.updatedAt = now(); await this.persistTask(task); }
  }
  async createDemoAsset(task, module) {
    const assetId = id('asset'); const outputDir = path.join(this.dataDir, 'assets'); const safe = String(task.input.prompt || 'AI image').replace(/[&<>]/g, '').slice(0, 120);
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024"><rect width="1024" height="1024" fill="#203334"/><rect x="72" y="72" width="880" height="880" fill="#f4f1e8"/><circle cx="512" cy="360" r="145" fill="#c78b6b"/><path d="M285 815c40-250 414-250 454 0" fill="#477b6c"/><text x="112" y="125" font-family="Arial" font-size="30" fill="#203334">${module.manifest.name} · DEMO</text><text x="112" y="900" font-family="Arial" font-size="24" fill="#203334">${safe}</text></svg>`;
    const localPath = path.join(outputDir, `${assetId}.svg`); await fs.writeFile(localPath, svg, 'utf8'); return { assetId, localPath, thumbnailPath: localPath, mimeType: 'image/svg+xml', width: 1024, height: 1024, url: `/api/assets/${assetId}` };
  }
  async cancelTask(taskId) { const task = this.tasks.get(taskId); if (!task) throw new PlatformError('TASK_NOT_FOUND', 'Task not found.'); if (['completed', 'failed', 'cancelled'].includes(task.status)) return task; task.status = 'cancelled'; task.updatedAt = now(); await this.persistTask(task); return task; }
  async persistTask(task) { await fs.writeFile(path.join(this.dataDir, 'history', `${task.taskId}.json`), JSON.stringify(task, null, 2)); }
  async loadHistory() { try { for (const entry of await fs.readdir(path.join(this.dataDir, 'history'))) { if (entry.endsWith('.json')) { const task = await json(path.join(this.dataDir, 'history', entry)); this.tasks.set(task.taskId, task); } } } catch {} }
  history(options = {}) { const all = [...this.tasks.values()].sort((a, b) => b.createdAt.localeCompare(a.createdAt)); const offset = Math.max(0, Number(options.offset || 0)); const limit = Math.min(100, Math.max(1, Number(options.limit || 20))); return { items: all.slice(offset, offset + limit), total: all.length, offset, limit, hasMore: offset + limit < all.length }; }
  async asset(assetId) { for (const task of this.tasks.values()) { const assets = [...(task.outputs || []), ...(task.results || [])]; const asset = assets.find((output) => output.assetId === assetId); if (asset) return asset; } try { return JSON.parse(await fs.readFile(path.join(this.dataDir, 'registry', `${assetId}.json`), 'utf8')); } catch { throw new PlatformError('LOCAL_FILE_NOT_FOUND', 'Generated asset is unavailable.'); } }
  errorFor(error, task) { return error instanceof PlatformError ? { ...error.toJSON(), taskId: task.taskId } : { code: 'UNKNOWN_ERROR', message: 'The task failed unexpectedly.', retryable: false, taskId: task.taskId }; }
}
